<!DOCTYPE html>
<link rel="stylesheet" href="css/contactstyle.css">

<div class="contactform">

	<div class="formbox">

		<form name="htmlform" method="post" action="toyousender.php">

			<input type="email" name="email" placeholder="MAIL" required>
			<input type="message" name="message" placeholder="MESSAGE" required>
			
			<button name="send" type="submit" class="submit">SEND</button>

		</form>

	</div>
</div>
