<!DOCTYPE html>
<link rel="stylesheet" href="css/shortstoriesstyle.css">


<div class="photos container-fluid">
	<a href="https://www.behance.net/gallery/37925411/Freak-Fruit"><img
		class="img-responsive"
		src="https://mir-s3-cdn-cf.behance.net/projects/404/100d2e37925411.Y3JvcCw0MTU5LDMyNTcsMzkyLDA.jpg" /></a>
	<a href="https://www.behance.net/gallery/37819633/Quinkessence"><img
		class="img-responsive"
		src="https://mir-s3-cdn-cf.behance.net/projects/404/ff8b5037819633.Y3JvcCwzMTg5LDI0OTEsNDk4LDg2OA.jpg" /></a>
</div>