<!DOCTYPE html>
<link rel="stylesheet" href="css/wallpaperstyle.css">

<div class="para">filler</div>

<!-- row is not my class but foot is, so i will style .foot and .foot-item -->
<div class="row foot">
	
	<div class="foot-item col-md-1 col-xs-2">
		<a href="https://www.facebook.com/sopan.tripathi"><span
			class="glyphicon glyphicon-thumbs-up"></span></a>
	</div>
	
	<div class="foot-item col-md-1 col-xs-2">
		<a href="https://www.iitb.ac.in"><span
			class="glyphicon glyphicon-education"></span></a>
	</div>
</div>